# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\CSCI3280\project\onlineChatroom\UI\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 842)
        MainWindow.setMinimumSize(QtCore.QSize(910, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.statusLayout = QtWidgets.QHBoxLayout()
        self.statusLayout.setObjectName("statusLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.statusLayout.addWidget(self.label_6)
        self.connectionMsg = QtWidgets.QLabel(self.centralwidget)
        self.connectionMsg.setObjectName("connectionMsg")
        self.statusLayout.addWidget(self.connectionMsg)
        self.gridLayout.addLayout(self.statusLayout, 0, 0, 1, 1)
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setStyleSheet("QFrame{\n"
"     border: 1px solid rgb(0, 0, 0)\n"
" }")
        self.verticalFrame.setObjectName("verticalFrame")
        self.userAndChatroomLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.userAndChatroomLayout.setObjectName("userAndChatroomLayout")
        self.NameTag = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameTag.sizePolicy().hasHeightForWidth())
        self.NameTag.setSizePolicy(sizePolicy)
        self.NameTag.setMinimumSize(QtCore.QSize(130, 0))
        self.NameTag.setStyleSheet("Border :none")
        self.NameTag.setObjectName("NameTag")
        self.userAndChatroomLayout.addWidget(self.NameTag)
        self.username = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMinimumSize(QtCore.QSize(130, 20))
        self.username.setMaximumSize(QtCore.QSize(130, 16777215))
        self.username.setObjectName("username")
        self.userAndChatroomLayout.addWidget(self.username)
        self.IPTag = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPTag.sizePolicy().hasHeightForWidth())
        self.IPTag.setSizePolicy(sizePolicy)
        self.IPTag.setMinimumSize(QtCore.QSize(130, 0))
        self.IPTag.setMaximumSize(QtCore.QSize(130, 16777215))
        self.IPTag.setStyleSheet("Border:none")
        self.IPTag.setObjectName("IPTag")
        self.userAndChatroomLayout.addWidget(self.IPTag)
        self.target_ip = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_ip.sizePolicy().hasHeightForWidth())
        self.target_ip.setSizePolicy(sizePolicy)
        self.target_ip.setMinimumSize(QtCore.QSize(130, 20))
        self.target_ip.setMaximumSize(QtCore.QSize(130, 16777215))
        self.target_ip.setObjectName("target_ip")
        self.userAndChatroomLayout.addWidget(self.target_ip)
        self.IPTag_2 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPTag_2.sizePolicy().hasHeightForWidth())
        self.IPTag_2.setSizePolicy(sizePolicy)
        self.IPTag_2.setMinimumSize(QtCore.QSize(130, 0))
        self.IPTag_2.setStyleSheet("Border:none")
        self.IPTag_2.setObjectName("IPTag_2")
        self.userAndChatroomLayout.addWidget(self.IPTag_2)
        self.chatroom_name = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatroom_name.sizePolicy().hasHeightForWidth())
        self.chatroom_name.setSizePolicy(sizePolicy)
        self.chatroom_name.setMinimumSize(QtCore.QSize(130, 20))
        self.chatroom_name.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chatroom_name.setObjectName("chatroom_name")
        self.userAndChatroomLayout.addWidget(self.chatroom_name)
        self.label_8 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setStyleSheet("Border:none")
        self.label_8.setObjectName("label_8")
        self.userAndChatroomLayout.addWidget(self.label_8)
        self.chatroom_port = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatroom_port.sizePolicy().hasHeightForWidth())
        self.chatroom_port.setSizePolicy(sizePolicy)
        self.chatroom_port.setMinimumSize(QtCore.QSize(130, 20))
        self.chatroom_port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chatroom_port.setObjectName("chatroom_port")
        self.userAndChatroomLayout.addWidget(self.chatroom_port)
        self.label = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setStyleSheet("Border:none")
        self.label.setObjectName("label")
        self.userAndChatroomLayout.addWidget(self.label)
        self.public_ip = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.public_ip.sizePolicy().hasHeightForWidth())
        self.public_ip.setSizePolicy(sizePolicy)
        self.public_ip.setMinimumSize(QtCore.QSize(130, 20))
        self.public_ip.setMaximumSize(QtCore.QSize(130, 16777215))
        self.public_ip.setObjectName("public_ip")
        self.userAndChatroomLayout.addWidget(self.public_ip)
        self.label_9 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(130, 0))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setStyleSheet("Border:none")
        self.label_9.setObjectName("label_9")
        self.userAndChatroomLayout.addWidget(self.label_9)
        self.local_ip = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_ip.sizePolicy().hasHeightForWidth())
        self.local_ip.setSizePolicy(sizePolicy)
        self.local_ip.setMinimumSize(QtCore.QSize(130, 20))
        self.local_ip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.local_ip.setObjectName("local_ip")
        self.userAndChatroomLayout.addWidget(self.local_ip)
        self.hostBtn = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostBtn.sizePolicy().hasHeightForWidth())
        self.hostBtn.setSizePolicy(sizePolicy)
        self.hostBtn.setMinimumSize(QtCore.QSize(130, 18))
        self.hostBtn.setObjectName("hostBtn")
        self.userAndChatroomLayout.addWidget(self.hostBtn)
        self.connectBtn = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectBtn.sizePolicy().hasHeightForWidth())
        self.connectBtn.setSizePolicy(sizePolicy)
        self.connectBtn.setMinimumSize(QtCore.QSize(130, 18))
        self.connectBtn.setObjectName("connectBtn")
        self.userAndChatroomLayout.addWidget(self.connectBtn)
        self.connectToLocalhost = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectToLocalhost.sizePolicy().hasHeightForWidth())
        self.connectToLocalhost.setSizePolicy(sizePolicy)
        self.connectToLocalhost.setMinimumSize(QtCore.QSize(130, 18))
        self.connectToLocalhost.setObjectName("connectToLocalhost")
        self.userAndChatroomLayout.addWidget(self.connectToLocalhost)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setStyleSheet("Border:none")
        self.label_4.setObjectName("label_4")
        self.userAndChatroomLayout.addWidget(self.label_4)
        self.connect_to_chat = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_to_chat.sizePolicy().hasHeightForWidth())
        self.connect_to_chat.setSizePolicy(sizePolicy)
        self.connect_to_chat.setMinimumSize(QtCore.QSize(130, 20))
        self.connect_to_chat.setMaximumSize(QtCore.QSize(130, 16777215))
        self.connect_to_chat.setObjectName("connect_to_chat")
        self.userAndChatroomLayout.addWidget(self.connect_to_chat)
        self.chatroom_list = QtWidgets.QListWidget(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatroom_list.sizePolicy().hasHeightForWidth())
        self.chatroom_list.setSizePolicy(sizePolicy)
        self.chatroom_list.setMinimumSize(QtCore.QSize(130, 200))
        self.chatroom_list.setMaximumSize(QtCore.QSize(130, 16777215))
        self.chatroom_list.setObjectName("chatroom_list")
        self.userAndChatroomLayout.addWidget(self.chatroom_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.userAndChatroomLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.verticalFrame, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.memberlist = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memberlist.sizePolicy().hasHeightForWidth())
        self.memberlist.setSizePolicy(sizePolicy)
        self.memberlist.setObjectName("memberlist")
        self.verticalLayout.addWidget(self.memberlist)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_title.sizePolicy().hasHeightForWidth())
        self.chat_title.setSizePolicy(sizePolicy)
        self.chat_title.setObjectName("chat_title")
        self.verticalLayout_3.addWidget(self.chat_title)
        self.chatbox = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatbox.sizePolicy().hasHeightForWidth())
        self.chatbox.setSizePolicy(sizePolicy)
        self.chatbox.setObjectName("chatbox")
        self.verticalLayout_3.addWidget(self.chatbox)
        self.ttsToggle = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ttsToggle.sizePolicy().hasHeightForWidth())
        self.ttsToggle.setSizePolicy(sizePolicy)
        self.ttsToggle.setObjectName("ttsToggle")
        self.verticalLayout_3.addWidget(self.ttsToggle)
        self.chat_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_input.sizePolicy().hasHeightForWidth())
        self.chat_input.setSizePolicy(sizePolicy)
        self.chat_input.setObjectName("chat_input")
        self.verticalLayout_3.addWidget(self.chat_input)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.StatusMsg = QtWidgets.QLabel(self.centralwidget)
        self.StatusMsg.setObjectName("StatusMsg")
        self.horizontalLayout.addWidget(self.StatusMsg)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tipsMessage = QtWidgets.QLabel(self.centralwidget)
        self.tipsMessage.setObjectName("tipsMessage")
        self.verticalLayout_4.addWidget(self.tipsMessage)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.push_to_talk = QtWidgets.QPushButton(self.centralwidget)
        self.push_to_talk.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/chatroom/numute.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.push_to_talk.setIcon(icon)
        self.push_to_talk.setIconSize(QtCore.QSize(50, 50))
        self.push_to_talk.setObjectName("push_to_talk")
        self.horizontalLayout_3.addWidget(self.push_to_talk)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.recording_tips = QtWidgets.QLabel(self.centralwidget)
        self.recording_tips.setObjectName("recording_tips")
        self.verticalLayout_4.addWidget(self.recording_tips)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.recording_voice = QtWidgets.QPushButton(self.centralwidget)
        self.recording_voice.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/chatroom/recording.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.recording_voice.setIcon(icon1)
        self.recording_voice.setIconSize(QtCore.QSize(50, 50))
        self.recording_voice.setObjectName("recording_voice")
        self.horizontalLayout_2.addWidget(self.recording_voice)
        self.play_recording = QtWidgets.QPushButton(self.centralwidget)
        self.play_recording.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/chatroom/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play_recording.setIcon(icon2)
        self.play_recording.setIconSize(QtCore.QSize(50, 50))
        self.play_recording.setObjectName("play_recording")
        self.horizontalLayout_2.addWidget(self.play_recording)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.stop_recording = QtWidgets.QPushButton(self.centralwidget)
        self.stop_recording.setEnabled(False)
        self.stop_recording.setObjectName("stop_recording")
        self.verticalLayout_4.addWidget(self.stop_recording)
        self.recording_list = QtWidgets.QListWidget(self.centralwidget)
        self.recording_list.setObjectName("recording_list")
        self.verticalLayout_4.addWidget(self.recording_list)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.ExtensionTag = QtWidgets.QTabWidget(self.centralwidget)
        self.ExtensionTag.setMinimumSize(QtCore.QSize(0, 400))
        self.ExtensionTag.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.ExtensionTag.setObjectName("ExtensionTag")
        self.voice = QtWidgets.QWidget()
        self.voice.setObjectName("voice")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.voice)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.karaoke_tips = QtWidgets.QLabel(self.voice)
        self.karaoke_tips.setObjectName("karaoke_tips")
        self.verticalLayout_7.addWidget(self.karaoke_tips)
        self.karaoke_path = QtWidgets.QLineEdit(self.voice)
        self.karaoke_path.setEnabled(False)
        self.karaoke_path.setObjectName("karaoke_path")
        self.verticalLayout_7.addWidget(self.karaoke_path)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.karaoke_select_file = QtWidgets.QPushButton(self.voice)
        self.karaoke_select_file.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.karaoke_select_file.setObjectName("karaoke_select_file")
        self.horizontalLayout_4.addWidget(self.karaoke_select_file)
        self.karaoke_upload_song = QtWidgets.QPushButton(self.voice)
        self.karaoke_upload_song.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.karaoke_upload_song.setObjectName("karaoke_upload_song")
        self.horizontalLayout_4.addWidget(self.karaoke_upload_song)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.voice)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.karaoke_song_list = QtWidgets.QListWidget(self.voice)
        self.karaoke_song_list.setObjectName("karaoke_song_list")
        self.verticalLayout_7.addWidget(self.karaoke_song_list)
        self.karaoke_refresh = QtWidgets.QPushButton(self.voice)
        self.karaoke_refresh.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.karaoke_refresh.setObjectName("karaoke_refresh")
        self.verticalLayout_7.addWidget(self.karaoke_refresh)
        self.karaoke_play = QtWidgets.QPushButton(self.voice)
        self.karaoke_play.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.karaoke_play.setObjectName("karaoke_play")
        self.verticalLayout_7.addWidget(self.karaoke_play)
        self.karaoke_stop_curr = QtWidgets.QPushButton(self.voice)
        self.karaoke_stop_curr.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.karaoke_stop_curr.setObjectName("karaoke_stop_curr")
        self.verticalLayout_7.addWidget(self.karaoke_stop_curr)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.ExtensionTag.addTab(self.voice, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pitchToggle = QtWidgets.QCheckBox(self.tab_2)
        self.pitchToggle.setObjectName("pitchToggle")
        self.verticalLayout_2.addWidget(self.pitchToggle)
        self.PitchSlider = QtWidgets.QSlider(self.tab_2)
        self.PitchSlider.setTabletTracking(False)
        self.PitchSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.PitchSlider.setMinimum(-100)
        self.PitchSlider.setMaximum(100)
        self.PitchSlider.setTracking(True)
        self.PitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PitchSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.PitchSlider.setTickInterval(50)
        self.PitchSlider.setObjectName("PitchSlider")
        self.verticalLayout_2.addWidget(self.PitchSlider)
        self.pitchValue = QtWidgets.QLabel(self.tab_2)
        self.pitchValue.setObjectName("pitchValue")
        self.verticalLayout_2.addWidget(self.pitchValue)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.ExtensionTag.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.ExtensionTag)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ExtensionTag.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "G12 Chatroom"))
        self.label_6.setText(_translate("MainWindow", "Connection:"))
        self.connectionMsg.setText(_translate("MainWindow", "[No connection]"))
        self.NameTag.setText(_translate("MainWindow", "Name"))
        self.username.setText(_translate("MainWindow", "ChanTaiMan"))
        self.IPTag.setText(_translate("MainWindow", "Chatroom Server IP"))
        self.target_ip.setText(_translate("MainWindow", "43.198.17.189"))
        self.IPTag_2.setText(_translate("MainWindow", "Chatroom name*"))
        self.chatroom_name.setText(_translate("MainWindow", "temp"))
        self.label_8.setText(_translate("MainWindow", "Chatroom port*"))
        self.chatroom_port.setText(_translate("MainWindow", "32800"))
        self.label.setText(_translate("MainWindow", "Public IP address*"))
        self.public_ip.setText(_translate("MainWindow", "43.198.17.189"))
        self.label_9.setText(_translate("MainWindow", "Local IP address*"))
        self.local_ip.setText(_translate("MainWindow", "172.31.13.35"))
        self.hostBtn.setText(_translate("MainWindow", "Host*"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.connectToLocalhost.setText(_translate("MainWindow", "Connect to localhost"))
        self.label_4.setText(_translate("MainWindow", "Chatroom List"))
        self.connect_to_chat.setText(_translate("MainWindow", "Connect to chatroom"))
        self.label_2.setText(_translate("MainWindow", "Member"))
        self.chat_title.setText(_translate("MainWindow", "Chat"))
        self.ttsToggle.setText(_translate("MainWindow", "Text to speech"))
        self.label_7.setText(_translate("MainWindow", "Status:"))
        self.StatusMsg.setText(_translate("MainWindow", "N/A"))
        self.tipsMessage.setText(_translate("MainWindow", "[Click the button to speak]"))
        self.label_10.setText(_translate("MainWindow", "Recording"))
        self.recording_tips.setText(_translate("MainWindow", "[Click the button to record]"))
        self.stop_recording.setText(_translate("MainWindow", "Stop Playback"))
        self.label_5.setText(_translate("MainWindow", "Extension"))
        self.karaoke_tips.setText(_translate("MainWindow", "[No one playing song now]"))
        self.karaoke_select_file.setText(_translate("MainWindow", "Select file"))
        self.karaoke_upload_song.setText(_translate("MainWindow", "Upload to host"))
        self.label_3.setText(_translate("MainWindow", "Song list:"))
        self.karaoke_refresh.setText(_translate("MainWindow", "Refresh list"))
        self.karaoke_play.setText(_translate("MainWindow", "Play the song"))
        self.karaoke_stop_curr.setText(_translate("MainWindow", "Stop the song"))
        self.ExtensionTag.setTabText(self.ExtensionTag.indexOf(self.voice), _translate("MainWindow", "Karaoke"))
        self.pitchToggle.setText(_translate("MainWindow", "Voice Changer"))
        self.pitchValue.setText(_translate("MainWindow", "Pitch: 0"))
        self.ExtensionTag.setTabText(self.ExtensionTag.indexOf(self.tab_2), _translate("MainWindow", "VC Change"))
import UI.icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
